### PR TITLE
Allowing source and country params in request phase

### PR DESCRIPTION
**Pull request by serenbean**

### CODE REVIEW

**Comment by luxerama** [comment]
@serenbean could we not use the app_id as source?

**Comment by serenbean** [comment]
`source` is used for registration/coreg combo, not to determine the app itself.

**Comment by luxerama** [comment]
@serenbean not sure i understand completely, what do you mean by

> registration/coreg combo

can you expand?

**Comment by serenbean** [comment]
Connect uses the same `app_id` throughout all brands, so we need `source` separately to know which brand it's coming from.

**Comment by luxerama** [comment]
So we should probably change that rather that add some domain specific knowledge to this gem

**Comment by serenbean** [comment]
Change what exactly?

**Comment by luxerama** [comment]
> Connect uses the same app_id throughout all brands

Based on what you are saying we should have an `app_id` for each brand

**Comment by luxerama** [comment]
Pseudo code:

```
config.omniauth  :studentbeans, setup: lambda do
  client_id = Brand.find.client_id
  client_secret = Brand.find.client_secret
end
```

**Comment by luxerama** [comment]
@serenbean just stumbled across this http://stackoverflow.com/a/16830847 as we are using Devise it might be better than the solution above.

**Comment by serenbean** [comment]
We don't have devise on connect but that looks exactly like this: https://github.com/intridea/omniauth/wiki/Setup-Phase

**Pull request closed without merging**
